sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2333
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-keyId: LTAI5tD5z7AEwe4RyrocUeUh
    accessKey-secret: ZIpUF3YUC46MmbX6DplzEF1gDglfd5
    bucket-name: sky-take-cys